#!/bin/zsh

function paste {
	url=$(curl -n -F 'f:1=<-' http://ix.io)

	echo "$url"
}

function extract() {
    for i in $*; do
        case $i in
            *.tar.gz)
                tar xzf $i
                ;;
            *.tar.bz2)
                tar xjf $i
                ;;
            *.zip|*.rar)
                7z x $i
                ;;
        esac
    done
}

function scut() {
    if [[ $# -ne 3 ]]; then
        print "Usage: scut START IN OUT" && return 0
    fi

    mencoder -ovc copy -oac copy -aid 1 -ss $1 "$2" -o "$3"
}

