#!/bin/zsh

function paste {
	url=$(curl -n -F 'f:1=<-' http://ix.io)

	echo "$url"
}

function extract() {
    for i in $*; do
        case $i in
            *.tar.gz)
                tar xzf $i
                ;;
            *.tar.bz2)
                tar xjf $i
                ;;
            *.zip|*.rar)
                7z x $i
                ;;
        esac
    done
}

